version: "3"
services:
  web:
    build:
      context: .
    image: qihr2022/tms-web
    networks:
      - backend
    ports:
      - "8090:8080"
    depends_on:
      - "db"
    volumes:
      - /usr/local/tomcat/webapps/ROOT/upload:/usr/local/tomcat/webapps/ROOT/upload
  db:
    build:
      context: ./db/mysql
    image: qihr2022/tms-db
    environment:
      - MYSQL_ROOT_PASSWORD=747576
    networks:
      - backend
    ports:
      - "3307:3306"
networks:
  backend: