version: "3"
services:
  web:
    image: qihr2022/tms-web
    networks:
      - backend
    ports:
      - "8090:8080"
    depends_on:
      - "db"
  db:
    image: qihr2022/tms-db
    environment:
      - MYSQL_ROOT_PASSWORD=747576
    networks:
      - backend
    ports:
      - "3307:3306"
networks:
  backend: