version: "3"
services:
  web:
    build:
      context: .
    image: tms-web
    networks:
      - backend
    ports:
      - "8090:8080"
    depends_on:
      - "db"
  db:
    build:
      context: ./db/postgres
    image: tms-db
    environment:
      - POSTGRES_PASSWORD=pingan
    networks:
      - backend
    ports:
      - "5433:5432"

networks:
  backend:
