apiVersion: v1
kind: Service
metadata:
  name: tms-svc
  namespace: default
  labels:
    app: tms
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
  selector:
    app: tms
